import { Inter } from "next/font/google";

import "./globals.css";
import { Download, Footer, Navbar } from "@/components";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import Providers from "./providers";
import dynamic from "next/dynamic";

const Modal = dynamic(()=> import("@/components/modal/Modal"),{
  ssr: false,
})


const inter = Inter({ subsets: ["latin"] });



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-red-100/30`}>
        <Providers>
          <Navbar />
          <Modal />
          {children}
          <Download />
          <Footer />
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
